comp_i2cmb_env_pkg:
	vlog +incdir+$(ECE745_PROJECT_HOME)/verification_ip/ncsu_pkg +incdir+$(ECE745_PROJECT_HOME)/verification_ip/environment_packages/i2cmb_env_pkg $(ECE745_PROJECT_HOME)/verification_ip/environment_packages/i2cmb_env_pkg/i2cmb_env_pkg.sv
	vlog $(ECE745_PROJECT_HOME)/verification_ip/environment_packages/i2cmb_env_pkg/src/i2cmb_probe_if.sv
	vlog +incdir+$(ECE745_PROJECT_HOME)/verification_ip/interface_packages/wb_pkg $(ECE745_PROJECT_HOME)/verification_ip/environment_packages/i2cmb_env_pkg/src/i2cmb_check_if.sv

